# Generated by Django 5.2.1 on 2025-05-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Discount'), ('category_based', 'Category-Based Discount')], max_length=20)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order total to qualify (for percentage discount)', max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 10 for 10%)', max_digits=5, null=True)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flat discount amount', max_digits=10, null=True)),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Minimum quantity required for category-based discount', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category for category-based discount', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
            },
        ),
    ]
